const menu = {
  id: 1331,
  submenus: [
    {
      id: 2,
      menu_type: "Standard",
      label: "Some('Default Server')",
      enabled: true,
      visible: true,
      icon_name: null,
      icon_data: null,
      shortcut: null,
      toggle_type: "CannotBeToggled",
      toggle_state: "On",
      children_display: null,
      disposition: "Normal",
      submenu: [
        {
          id: 26,
          menu_type: "Standard",
          label: "Some('ryu')",
          enabled: true,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "Radio",
          toggle_state: "On",
          children_display: null,
          disposition: "Normal",
          submenu: []
        }
      ]
    },
    {
      id: 4,
      menu_type: "Standard",
      label: "Some('Default Sink')",
      enabled: true,
      visible: true,
      icon_name: null,
      icon_data: null,
      shortcut: null,
      toggle_type: "CannotBeToggled",
      toggle_state: "On",
      children_display: null,
      disposition: "Normal",
      submenu: [
        {
          id: 27,
          menu_type: "Standard",
          label: "Some('Rembrandt Radeon High Definition Audio Controller Pro  45%')",
          enabled: true,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "Radio",
          toggle_state: "On",
          children_display: null,
          disposition: "Normal",
          submenu: []
        },
        {
          id: 28,
          menu_type: "Standard",
          label: "Some('Rembrandt Radeon High Definition Audio Controller Pro 7 100%')",
          enabled: true,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "Radio",
          toggle_state: "Off",
          children_display: null,
          disposition: "Normal",
          submenu: []
        },
        {
          id: 29,
          menu_type: "Standard",
          label: "Some('Rembrandt Radeon High Definition Audio Controller Pro 8 100%')",
          enabled: true,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "Radio",
          toggle_state: "Off",
          children_display: null,
          disposition: "Normal",
          submenu: []
        },
        {
          id: 30,
          menu_type: "Standard",
          label: "Some('Rembrandt Radeon High Definition Audio Controller Pro 9 100%')",
          enabled: true,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "Radio",
          toggle_state: "Off",
          children_display: null,
          disposition: "Normal",
          submenu: []
        },
        {
          id: 31,
          menu_type: "Standard",
          label: "Some('Family 17h/19h HD Audio Controller Speaker + Headphones 105%')",
          enabled: true,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "Radio",
          toggle_state: "Off",
          children_display: null,
          disposition: "Normal",
          submenu: []
        },
        {
          id: 422,
          menu_type: "Standard",
          label: "Some('UC02 Analog Stereo  40%')",
          enabled: true,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "Radio",
          toggle_state: "Off",
          children_display: null,
          disposition: "Normal",
          submenu: []
        }
      ]
    },
    {
      id: 6,
      menu_type: "Standard",
      label: "Some('Default Source')",
      enabled: true,
      visible: true,
      icon_name: null,
      icon_data: null,
      shortcut: null,
      toggle_type: "CannotBeToggled",
      toggle_state: "On",
      children_display: null,
      disposition: "Normal",
      submenu: [
        {
          id: 32,
          menu_type: "Standard",
          label: "Some('Family 17h/19h HD Audio Controller Headphones Stereo Microphone 100%')",
          enabled: true,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "Radio",
          toggle_state: "Off",
          children_display: null,
          disposition: "Normal",
          submenu: []
        },
        {
          id: 33,
          menu_type: "Standard",
          label: "Some('Family 17h/19h HD Audio Controller Digital Microphone  94%')",
          enabled: true,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "Radio",
          toggle_state: "On",
          children_display: null,
          disposition: "Normal",
          submenu: []
        },
        {
          id: 423,
          menu_type: "Standard",
          label: "Some('UC02 Mono 100%')",
          enabled: true,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "Radio",
          toggle_state: "Off",
          children_display: null,
          disposition: "Normal",
          submenu: []
        }
      ]
    },
    {
      id: 8,
      menu_type: "Standard",
      label: "Some('Playback Streams')",
      enabled: true,
      visible: true,
      icon_name: null,
      icon_data: null,
      shortcut: null,
      toggle_type: "CannotBeToggled",
      toggle_state: "On",
      children_display: null,
      disposition: "Normal",
      submenu: [
        {
          id: 700,
          menu_type: "Standard",
          label: "Some('none')",
          enabled: false,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "CannotBeToggled",
          toggle_state: "On",
          children_display: null,
          disposition: "Normal",
          submenu: []
        }
      ]
    },
    {
      id: 10,
      menu_type: "Standard",
      label: "Some('Recording Streams')",
      enabled: true,
      visible: true,
      icon_name: null,
      icon_data: null,
      shortcut: null,
      toggle_type: "CannotBeToggled",
      toggle_state: "On",
      children_display: null,
      disposition: "Normal",
      submenu: [
        {
          id: 11,
          menu_type: "Standard",
          label: "Some('none')",
          enabled: false,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "CannotBeToggled",
          toggle_state: "On",
          children_display: null,
          disposition: "Normal",
          submenu: []
        }
      ]
    },
    {
      id: 12,
      menu_type: "Standard",
      label: "Some('Modules')",
      enabled: true,
      visible: true,
      icon_name: null,
      icon_data: null,
      shortcut: null,
      toggle_type: "CannotBeToggled",
      toggle_state: "On",
      children_display: null,
      disposition: "Normal",
      submenu: [
        {
          id: 34,
          menu_type: "Standard",
          label: "Some('libpipewire-module-rt')",
          enabled: true,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "CannotBeToggled",
          toggle_state: "On",
          children_display: null,
          disposition: "Normal",
          submenu: []
        },
        {
          id: 35,
          menu_type: "Standard",
          label: "Some('libpipewire-module-protocol-native')",
          enabled: true,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "CannotBeToggled",
          toggle_state: "On",
          children_display: null,
          disposition: "Normal",
          submenu: []
        },
        {
          id: 36,
          menu_type: "Standard",
          label: "Some('libpipewire-module-profiler')",
          enabled: true,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "CannotBeToggled",
          toggle_state: "On",
          children_display: null,
          disposition: "Normal",
          submenu: []
        },
        {
          id: 37,
          menu_type: "Standard",
          label: "Some('libpipewire-module-metadata')",
          enabled: true,
          visible: true,
          icon_name: null,
          icon_data: null,
          shortcut: null,
          toggle_type: "CannotBeToggled",
          toggle_state: "On",
          children_display: null,
          disposition: "Normal",
          submenu: []
        },
      ]
    }
  ]
};